[package]
name = "bloom-goes-boom"
version = "0.1.0"
edition = "2021"

[dependencies]
xxh3 = "0.1"
bytevec = "0.2"
topk = "0.5"
rand = "0.8"
num_cpus = "1.16"
structopt = "0.3"
rayon = "1.10.0"
fftw = "0.8.0"
num = "0.4"
num-bigint = "0.4"
cached = "0.54"
